FROM jenkins/jenkins:2.283-centos7

USER root

RUN yum update -y
RUN yum update -y

RUN yum install -y python3-pip
RUN pip3 install --upgrade pip
RUN yum install -y maven
RUN pip3 install ansible --upgrade
RUN yum install -y sshpass

USER jenkins
