FROM ubuntu:20.04

RUN apt update && \
 apt install -y openssh-server

RUN useradd remote_user && \
    echo "remote_user:1234" | chpasswd && \
    mkdir /home/remote_user/.ssh -p && \
    chmod 700 /home/remote_user/.ssh && \
    mkdir -p -m0755 /var/run/sshd

# COPY remote-key.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user   -R /home/remote_user && \
    chmod 400 /home/remote_user/.ssh/authorized_keys

RUN  apt update && \
     apt install -y openjdk-11-jdk && \
     apt install -y git && \
     apt install -y maven

CMD /usr/sbin/sshd -D
